name: Run Python Script Daily

on:
  # [push]
  schedule:
    - cron: '0 05 21 * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    environment: shifts_env 
    env:
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      SENDER_ADDRESS: ${{ secrets.SENDER_ADDRESS }}
      RECEIVER_MAIL: ${{ secrets.RECEIVER_MAIL }}
      SHIFTS_LINK: ${{ secrets.SHIFTS_LINK }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python arrangements/main.py
